name: Add New Issue to Project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.0
        with:
          # You can target a project in a different organization
          # to the issue
          project-url: https://github.com/orgs/untamed-team/projects/16
          github-token: ${{ secrets.PROJECT_BOARD_AUTOMATION }}
          labeled: art
          label-operator: OR
  
  add-to-column:
    name: Add issue to column based on label
    if: github.action.label == 'art'
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.9.0
        with:
          project: Project Untamed Progress Overview
          column: Art
          repo-token: ${{ secrets.PROJECT_BOARD_AUTOMATION }}