name: Move new issues into Project Boards
on:
  issues:
    types: [ labeled ]
jobs:
  move-issue-to-organization-project-column:
    name: Move issues to organization project column
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to 'To do' column if body has a mark 'issue:todo'
        uses: fojia/action-move-issues-to-column@master
        with:
          project: 'Project Untamed Progress Overview'
          column: 'Assigned'
          owner: 'fojia'
          type: 'org'
          github_token: ${{ secrets.PROJECT_BOARD_AUTOMATION }}
          label: 'code'