on:
  issues:
    types: [labeled]
jobs:
  Move_Labeled_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.0]
    
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.PROJECT_BOARD_AUTOMATION }}"
        project-url: "https://github.com/orgs/untamed-team/projects/16"
        column-name: "Assigned"
        label-name: "code"
        columns-to-ignore: "Done Recently"